name: llms
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - python=3.9
  - jupyter
  - jupyterlab
  - matplotlib
  - numpy
  - pandas
  - pip
  - requests
  - pip:
      - accelerate
      - autopep8
      - beautifulsoup4
      - bert-score
      - chromadb
      - datasets
      - diffusers
      - evaluate
      - huggingface_hub
      - instructor
      - joblib
      - langchain[all]
      - langchain-openai
      - langchain-community
      - lxml
      - ollama
      - openai
      - pydantic
      - pypdf
      - pytest
      - python-dotenv
      - safetensors
      - scikit-learn
      - sentence-transformers
      - setuptools
      - torch
      - torchaudio
      - torchtext
      - torchvision
      - transformers
      - transformers[torch]
      - wheel
      - wikipedia